### ISSUE TITLE
JsonDecode(ApplicationError("No field for inferring message type is set"))

### ISSUE THREAD

**Issue by chihiro** [telegram-rs/telegram-bot#31] opened 2016-03-06 12:57 UTC
Hi, I'm getting this error for a message when trying to use the library.

`JsonDecode(ApplicationError("No field for inferring message type is set"))`
Seems like it's encountering a message type the library doesn't know?

I can give you the source code if needed but it's almost the same as the example.
If you can't reproduce it I am willing to give you the bot token so you can see it happening.

Also taking a look at trying to fix it myself, but I cannot promise anything on that front.

**Comment by rein** [comment] 2016-03-06 21:17
Deleted and recreated the bot and it started working again. I still don't know what caused this. I modified the library to print every message it decodes in JSON form and that told me roughly where the crash was, but I couldn't see anything that might've caused it.

**Comment by LukasKalbertodt** [comment] 2016-03-06 21:33
Thanks for your report! It would be great if you could provide a minimal example that has this behavior. We might try to reproduce the bug on our own some time in the future; sadly I am pretty busy for at least a week still.

But your issue made me think, that we could include more logging for debugging purposes -- preferably via the official `log` crate.

**Comment by rein** [comment] 2016-03-06 22:08
Thanks for the reply.

I can't provide an example at the moment because as far as I can tell it's a certain type of message that caused it. I've deleted the bot which the problem was happening with and created a new one, which fixed it (as it started fresh from the newest message). The library is working perfectly so far.

If I encounter the issue again I'll determine how to reproduce it.

**Comment by knsd** [comment] 2017-04-29 07:52
I believe this issue was resolved in 0.5.0.

**Closed by knsd** 2017-04-29 07:52 UTC
Labels: bug, pre-rewrite
